name: Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false   # don’t cancel other shards on one failure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'              # 🔥 cache node_modules

      - name: Install deps
        run: npm ci                 # faster & consistent than npm install

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Run tests
        env:
          CI: true
          BASE_URL: https://demo.nopcommerce.com
        run: npx playwright test

      # Always upload artifacts (even if tests fail)
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload test results (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: results.xml

      - name: Generate Allure report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate ./allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report